### ISSUE TITLE
H 4  or V 4 (with a space after the H or V fails but its valid svg syntax

### ISSUE THREAD

**Issue by paultz54** [masterashu/svg_path_parser#3]
currently  
  /// Fetch a single float value src/scanner.dart/_fetchSingleCoordinate() 
  _fetchSingleCoordinate() {
    _fetchFloatValue();
    _skipWhitespace();
  }

should be (in my not very expert opinion)

 _fetchSingleCoordinate() {
   _skipWhitespace();
    _fetchFloatValue();
    _skipWhitespace();
  }

**Comment by masterashu** [comment]
Okay will look into that.

**Comment by masterashu** [comment]
Closed by c068a57

Thanks for the tip.
