### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by RyanRamchandar** [masterashu/svg_path_parser#4]
Now that Flutter 2.0 and Dart 2.12 are out, this package should be migrated to sound null safety to not block apps that also want to upgrade to null safety.

https://dart.dev/null-safety/migration-guide

**Comment by masterashu** [comment]
Thanks, I will migrate this weekend.

**Comment by masterashu** [comment]
Closed by c068a57

**Comment by RyanRamchandar** [comment]
Thanks @masterashu !
