### ISSUE TITLE
Save Path Object as svg path string.

### ISSUE THREAD

**Issue by deepu** [masterashu/svg_path_parser#5]
Hey, Thanks for creating this package. It's super helpful. 

I am trying to create a Drawing application in Flutter. My use case is , import any existing SVG -> Make changes -> Export to SVG. . 

This library is super helpful for importing any SVG as Path Objects. I can manipulate the same using certain gestures but I am stuck at the last step, how to save the path objects back as SVG path strings ?

**Comment by masterashu** [comment]
Thanks.
Let me see what can be done. 👍🏽

**Comment by masterashu** [comment]
Looks like the reverse isn't entirely possible.

> Path components Arc, Rect, Round_Rect, Circle, and Oval are composed of Lines and Curves with as many Verbs and Points required for an exact description. Once added to Path, these components may lose their identity; although Path can be inspected to determine if it describes a single Rect, Oval, Round_Rect, and so on.

https://skia.org/docs/user/api/skpath_overview

**Comment by masterashu** [comment]
However, if the serialize API of `SkipPath` was exposed in dart code. It can be done.

https://api.skia.org/classSkPath.html#aa82edaf919c551e5db352fd80f1aeed4

you can try asking guys at flutter for exposing that.

**Comment by masterashu** [comment]
@deepu Refer here
https://github.com/flutter/flutter/issues/18458#issuecomment-409953397

**Comment by deepu** [comment]
If possible can I connect with you ? 

Is the email address on your GitHub profile the right place to reach you ?

**Comment by masterashu** [comment]
Yes, You can add me on Discord, I will online tomorrow. `masterashu#2959`
