### ISSUE TITLE
Error in SVG path grammar:  flag

### ISSUE THREAD

**Issue by zathras** [masterashu/svg_path_parser#6]
The Path grammar's flag regexp is incorrect, in a way that causes the parser to fail on a valid path that I encountered in a real SVG image.  It's a fine point.  The fix is easy:  over on line 74 of `scanner.dart`, this:
```
  static final flagPattern = RegExp(r'(0|1)(?=[,\s])');
```
should be:
```
  static final flagPattern = RegExp(r'(0|1)');
```

The SVG path grammar is a little surprising here, but check out https://www.w3.org/TR/2018/CR-SVG2-20181004/paths.html#TheDProperty .  No ambiguity here:
```
flag::=("0"|"1")
```
There is no requirement that a flag be followed by whitespace or a comma.  "00" is two flags, both zero, even though they're not separated by anything.  I verified this:  The following svg is valid (according to https://validator.w3.org/check), and it also renders correctly in a browser (Firefox):
```
<?xml version="1.0" encoding="UTF-8"?>
<svg style="height: 512px; width: 512px;" xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 512 512">
<path d=
"M104.247 91.68a224 224 0 00-30.668 34.84l355.482-12.694a224 224 0 00-21.065-22.146h-303.75z"
fill="#000000" fill-opacity="1">
</path>
</svg>
 
```
Note the a command, where "00-30.668" is flag 0, followed by flag 0, followed by -30.668.  Same thing again on the next a command.

**Comment by masterashu** [comment]
Working on it.
