### ISSUE TITLE
errors in paths containing mixed absolute and relative commands

### ISSUE THREAD

**Issue by eae1212** [masterashu/svg_path_parser#7]
if path contains only relative commands, like d="M 1031,175 v 150 h 8 v 16 h 92 v -16 h 6 v -150 z", SvgPathParser works ok.

if after relative commands there are absolute commands like d="M 1031,175 v 150 h 8 v 16 h 92 v -16 h 6 **V 175 H 1031 z**", SvgPathParser generates wrong  Path. It looks like parser ignores absolute commands.

**Comment by masterashu** [comment]
I will look it up.

**Comment by eae1212** [comment]
Hello, have you did any chance to look it up?

**Comment by masterashu** [comment]
I am currently looking it up

**Comment by masterashu** [comment]
@eae1212 Found the issue.
What I did
```dart
_currentPoint.translate(x,y)
```
What I should have
```dart
_currentPoint = _currentPoint.translate(x,y)
```

**Comment by masterashu** [comment]
You can get version `1.1.0` from pub.dev.

**Comment by eae1212** [comment]
Thanks a lot! It works great!
